spring:
  datasource:
    url: jdbc:mysql://localhost:3306/md_db
    username: maulik
    password: maulik9958
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true

